"""empty message

Revision ID: eafaaf9c3a42
Revises: 2c189d5f1c55
Create Date: 2023-11-05 15:48:19.123806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafaaf9c3a42'
down_revision = '2c189d5f1c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('head_img')

    # ### end Alembic commands ###
